name: CreativeControl
version: 5.8.1
author: FurmigaHumana
description: Keep yours creatives in the line!
main: me.FurH.CreativeControl.CreativeControl
softdepend: ['Vault', 'WorldEdit', 'LogBlock', 'AuthMe', 'xAuth', 'MobArena', 'Multiverse-Inventories', 'FCoreLib', 'SurvivalGames']
commands:
  creativecontrol:
    aliases: [cc, ccontrol]
    description: CreativeControl Commands
    usage: /creativecontrol help