Database:
  ## MySQL, the database type, can be SQLite, MySQL or H2
  Type: SQLite
  ## host, the MySQL host name
  host: localhost
  ## port, the MySQL port
  port: 3306
  ## user, the MySQL user name
  user: root
  ## pass, the MySQL password, '' if none.
  pass: 123
  ## database, the MySQL database to be used by this plugin
  database: minecraft
  ## prefix, the prefix used to create the tables in the sql database
  prefix: crcr_

## This section will define which group the player will be added when he changes his gamemode.
Permissions:
  ## Enabled, if true, this system will be enabled, in way to use this, you must set it to true.
  Enabled: false
  ## Move, if true, the player will be removed from his original group and added to the creative group, by default the player is just added to the new group.
  Move: false
  ## MoveFrom, the group that will be affected when the player change his gamemode, the player will only be moved if he is a member of this group.
  MoveFrom: MembersSurvival
  ## MoveTo, the group that the player will be added when he change his gamemode to creative
  MoveTo: MembersCreative
  ## OpHasPerm, if true, ops will have all the permissions and will not be checked by your permissions plugin
  OpHasPerm: false

## if you have an larger server with tons of creative players placing/breaking blocks, you should increase the "count" and decrease the "sleep" and "each"
Queue:
  ## each, set here, the time in milliseconds to wait after each execution. (1000 = 1 second)
  each: 50
  ## count, set here, the number of queries to run after make a bigger pause
  count: 50
  ## sleep, set here, the time in milliseconds to wait after the count being reached. (1000 = 1 second)
  sleep: 5000

Cache:
  ## MaxCapacity, the maximum cache capacity, higher this value is, better will be the performance, but also the memory usage will increase.
  MaxCapacity: 15000
  ## PreCache, the amount of items to be cached on startup, if you have a big database, this may increase the load time.
  PreCache: 10000

Configurations:
  ## Single, if true, only the world.yml file will be used, other ones will be ignored.
  Single: false
  ## Conflict, if true, if required, some functions of this plugin will be automatically disabled to avoid conflict.
  Conflict: true
  ## FriendSystem, if true, the friend system will be enabled, this may take a bit of resources, just a bit.
  FriendSystem: false

Updater:
  ## Check for updates?
  Enabled: true

Selection:
  ## UseWorldEdit, if true, worldedit will be used to make selections. Otherwise the tool defined below will be used.
  UseWorldEdit: true
  ## The Item ID used to select regions, if UseWorldEdit is false
  Tool: 369

Events:
  ## Use PlayerMoveEvent? This may take a lot of resources on large servers, but is required to Creative/Survival regions work.
  PlayerMove: false
  ## Enable MiscProtections? Not recommended to use, I'll probably remove it on future releases.
  MiscProtection: false

PlayerData:
  ## Inventory, if true, players will have an inventory to survival, other to creative an other to adventurer
  Inventory: true
  ## Status, if true, will save the player survival status [e.g Health, Food, etc]
  Status: true
  ## Teleport, if true, the player will be teleported to the floor on login if needed
  Teleport: false
  ## SetSurvival, if true, the player will be set to survival on login (ATTENTTION: THIS MAY GLITCH WITH AUTH PLUGINS)
  SetSurvival: false
  
## This section will define the armor to set on every creative player, for advanced options, while wearing the armor type /cc set armor.
CreativeArmor:
  ## Helmet, the player helmet
  Helmet: 0
  ## Chestplate, the player chestplate
  Chestplate: 0
  ## Leggings, the player leggings
  Leggings: 0
  ## Boots, the player boots
  Boots: 0

Communicator:
  ## Quiet, if true, any messages will be displayed
  Quiet: false

Debug:
  ## Console, if true, debug messages will be displayed in the console
  Console: false
  ## Stack, if true, common errors will be printed by full [leave it true C:]
  Stack: true