Database:
  ## MySQL, the database type, can be SQLite, MySQL or H2.
  Type: SQLite
  ## host, the MySQL host name
  host: localhost
  ## port, the MySQL port
  port: 3306
  ## user, the MySQL user name
  user: root
  ## pass, the MySQL password
  pass: 123
  ## database, the MySQL database to be used by this plugin
  database: minecraft
  ## prefix, the prefix used to create the tables in the sql database
  prefix: crcr_

## this section will define wich group the player will be added when he change his gamemode to creative, the player will not be removed from his original group
Permissions:
  ## Enabled, if true, this system will be used
  Enabled: false
  ## Move, if true, the player will be removed from his original group and added to the creative group
  Move: false
  ## MoveFrom, the group that will be affected when the player change his gamemode
  MoveFrom: MembersSurvival
  ## MoveTo, the group that the player will be added when he change his gamemode to creative
  MoveTo: MembersCreative

## if you have an larger server with tons of creative players placing/breaking blocks, you should increase the "count", decrease the "sleep" and "each"
Queue:
  ## each, set here, the time in milliseconds to wait after each execution.
  each: 50
  ## count, set here, the number of queries to run after make a bigger pause
  count: 50
  ## sleep, set here, the time in milliseconds to wait after the count being reached.
  sleep: 5000

Cache:
  ## MaxCapacity, the maximum cache capacity, higher this value is, better will be the performance, but also the memory usage will increase.
  MaxCapacity: 15000
  ## PreCache, the amount of items to be cached on startup
  PreCache: 10000

Configurations:
  ## Single, if true, only the world.yml file will be used, other ones will be ignored.
  Single: false
  ## Conflict, if true, if required, some functions of this plugin will be automatically disabled to avoid conflict.
  Conflict: true
  ## FriendSystem, if true, the friend system will be enabled, this may take a bit of resources, just a bit.
  FriendSystem: false

Updater:
  ## Check for updates?
  Enabled: true

Selection:
  ## UseWorldEdit, if true, worldedit will be used to make selections.
  UseWorldEdit: true
  ## The Item ID used to select regions, if UseWorldEdit is false
  Tool: 369

Events:
  ## Use Player Move Event? This may take a lot of resources on large servers, but is required to Creative/Survival regions work.
  PlayerMove: false
  ## Enable MiscProtections? This may take some extra resource, but will be much more comfortable to play with creative mode.
  MiscProtection: false

PlayerData:
  ## Inventory, if true, will have an inventory to survival and other to creative
  Inventory: true
  ## Status, if true, will save the player survival status [e.g Health, Food, etc]
  Status: true
  ## Teleport, if true, the player will be teleported to the floor on login if needed
  Teleport: false
  ## SetSurvival, if true, the player will be set to survival on login (ATTENTTION: THIS MAY GLITCH WITH AUTH PLUGINS)
  SetSurvival: false

Communicator:
  ## Quiet, if true, any messages will be displayed
  Quiet: false

Debug:
  ## Console, if true, debug messages will be displayed in the console
  Console: false
  ## Stack, if true, common errors will be printed by full [leave it true C:]
  Stack: true